spring:
  application:
    name: ms-order

  datasource:
    url: jdbc:MySql://localhost:3307/order_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          lob:
            non_contextual_creation: true

server:
  port: 8081

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /v3/api-docs

grpc:
  server:
      address: "localhost"
      port: "9090"
      enableKeepAlive: true


