version: '3.8'
services:
  db:
    image: mysql/mysql-server:latest
    container_name: my-mysql-order
    restart: always
    environment:
      - MYSQL_DATABASE=order_db
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3307:3306'
    volumes:
      - mysql-volume:/var/lib/mysql
volumes:
  mysql-volume:
    driver: local
